name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "./docker-compose.yaml"
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          RPC_URL_SEPOLIA: ${{ secrets.RPC_URL_SEPOLIA }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /bin/bash <<'ENDSSH'
          cd ${{ secrets.APP_PATH }}
          git pull origin main
          export DATABASE_URI=${{ secrets.DATABASE_URI }}
          export RPC_URL_SEPOLIA=${{ secrets.RPC_URL_SEPOLIA }}
          docker compose -f docker-compose.yaml up -d --build
          ENDSSH
